version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: process
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_application
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fcm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - app-network
volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
